---
- block:
    - name: Removing auter crontab file
      file:
        path: /etc/cron.d/auter
        state: absent

    - name: Applying auter cronjob configuration
      cron:
        cron_file: /etc/cron.d/auter
        name: "{{ item.name }}"
        job: "{{ item.job }}"
        minute: "{{ item.minute }}"
        hour: "{{ item.hour }}"
        weekday: "{{ item.weekday }}"
        day: "{{ item.day }}"
        month: "{{ item.month }}"
        state: present
        user: root
      with_items: "{{ auter_cronjobs }}"
  tags: auter
  when: auter_cronjobs is defined
...
