---
- name: Applying auter cronjob configuration
  cron:
    cron_file: /etc/cron.d/auter
    day: "{{ item.day|default(omit) }}"
    hour: "{{ item.hour|default(omit) }}"
    job: "{{ item.job }}"
    minute: "{{ item.minute|default(omit) }}"
    month: "{{ item.month|default(omit) }}"
    name: "{{ item.name }}"
    special_time: "{{ item.special_time|default(omit) }}"
    state: "{{ item.state|default('present') }}"
    user: "{{ item.user|default('root') }}"
    weekday: "{{ item.weekday|default(omit) }}"
  with_items: "{{ auter_cronjobs }}"
  when:
    - item.job is defined
    - item.name is defined
...
