---
- name: Ensure that the auter package is installed
  tags: auter
  become: true
  yum:
    enablerepo: epel
    name: auter
    state: present
  register: auter_yum

- name: Attempting to overlay auter configurations
  tags: auter
  become: true
  template:
    src: auter.conf.j2
    dest: /etc/auter/auter.conf
    owner: root
    group: root
    mode: 0644
  when: auter_yum is success

- name: Attempting to overlay auter script directories
  tags: auter
  become: true
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - "{{ auter_postprepscriptdir }}"
    - "{{ auter_postapplyscriptdir }}"
    - "{{ auter_postrebootscriptdir }}"
    - "{{ auter_preprepscriptdir }}"
    - "{{ auter_preapplyscriptdir }}"
    - "{{ auter_prerebootscriptdir }}"
  when: auter_yum is success

- name: Attempting to overlay auter cronjobs, if applicable
  tags: auter
  become: true
  cron:
    cron_file: /etc/cron.d/auter
    day: "{{ item.day|default(omit) }}"
    hour: "{{ item.hour|default(omit) }}"
    job: "{{ item.job }}"
    minute: "{{ item.minute|default(omit) }}"
    month: "{{ item.month|default(omit) }}"
    name: "{{ item.name }}"
    special_time: "{{ item.special_time|default(omit) }}"
    state: "{{ item.state|default('present') }}"
    user: "{{ item.user|default('root') }}"
    weekday: "{{ item.weekday|default(omit) }}"
  with_items: "{{ auter_cronjobs }}"
  when:
    - auter_cronjobs|length > 0
    - auter_yum is success
    - item.job is defined
    - item.name is defined

- name: Attempting to overlay auter pre-prep scripts, if applicable
  tags: auter
  become: true
  template:
    src: "{{ item.name }}"
    dest: "{{ auter_preprepscriptdir }}/{{ item.name }}"
    owner: root
    group: root
    mode: "{{ item.mode|default(0750) }}"
  with_items: "{{ auter_preprepscripts }}"
  when:
    - auter_preprepscripts|length > 0
    - auter_yum is success
    - item.name is defined
    

- name: Attempting to overlay auter post-prep scripts, if applicable
  tags: auter
  become: true
  template:
    src: "{{ item.name }}" 
    dest: "{{ auter_postprepscriptdir }}/{{ item.name }}"
    owner: root
    group: root
    mode: "{{ item.mode|default(0750) }}"
  with_items: "{{ auter_postprepscripts }}"
  when:
    - auter_postprepscripts|length > 0
    - auter_yum is success
    - item.name is defined
    


- name: Attempting to overlay auter pre-apply scripts, if applicable
  tags: auter
  become: true
  template:
    src: "{{ item.name }}"
    dest: "{{ auter_preapplyscriptdir }}/{{ item.name }}"
    owner: root
    group: root
    mode: "{{ item.mode|default(0750) }}"
  with_items: "{{ auter_preapplyscripts }}"
  when:
    - auter_preapplyscripts|length > 0
    - auter_yum is success
    - item.name is defined
    

- name: Attempting to overlay auter post-apply scripts, if applicable
  tags: auter
  become: true
  template:
    src: "{{ item.name }}"
    dest: "{{ auter_postapplyscriptdir }}/{{ item.name }}"
    owner: root
    group: root
    mode: "{{ item.mode|default(0750) }}"
  with_items: "{{ auter_postapplyscripts }}"
  when:
    - auter_postapplyscripts|length > 0
    - auter_yum is success
    - item.name is defined
    

- name: Attempting to overlay auter pre-reboot scripts, if applicable
  tags: auter
  become: true
  template:
    src: "{{ item.name }}"
    dest: "{{ auter_prerebootscriptdir }}/{{ item.name }}"
    owner: root
    group: root
    mode: "{{ item.mode|default(0750) }}"
  with_items: "{{ auter_prerebootscripts }}"
  when:
    - auter_prerebootscripts|length > 0
    - auter_yum is success
    - item.name is defined
    

- name: Attempting to overlay auter post-reboot scripts, if applicable
  tags: auter
  become: true
  template:
    src: "{{ item.name }}"
    dest: "{{ auter_postrebootscriptdir }}/{{ item.name }}"
    owner: root
    group: root
    mode: "{{ item.mode|default(0750) }}"
  with_items: "{{ auter_postrebootscripts }}"
  when:
    - auter_postrebootscripts|length > 0
    - auter_yum is success
    - item.name is defined
    

- name: Ensure that auter is started and enabled on boot
  tags: auter
  become: true
  command: |
    /bin/auter --enable
  when: auter_yum is success
